### ISSUE TITLE
CreateSwap should have 'market' prop

### ISSUE THREAD

**Issue by OAXFoundation** [OAXFoundation/swapdex#6]
If user is viewing ABC/DEF market and clicks create swap, we should set the market to ABC/DEF.

Right now it defaults to OAX/ETH b/c of hard coding in the useState of CreateSwap component

**Comment by waylandc** [comment]
implemented in [this commit](https://github.com/OAXFoundation/swapdex/commit/77ff2669de1db09cc7d498d818a24e67d574e3cd)
